name: Possum
favicon: null
layout_spectrum: 0.12700980016961694
typography_spectrum: 0.7633657527621835
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7562763607129455
  lightness: 0.5594432763755322
  saturation: 0.7297670538537204
  rhythmicContrast: 0.18555737100541592
purpose: []
